version: "3.8"

services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: true-roots-backend
    restart: always
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: true-roots-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=${PORT}
      - AUTH_SECRET=${AUTH_SECRET}
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
